name: Feature Request
description: Simple feature request form
title: "[FEATURE] "
labels: ["enhancement"]
assignees:
  - lukaszgrudnik

body:
  - type: textarea
    id: feature_description
    attributes:
      label: Description
      placeholder: "Describe the feature you'd like to see"
    validations:
      required: true
